driver:
  name: docker
<% if /darwin/ =~ RUBY_PLATFORM %>
  use_sudo: false
<% end %>

provisioner:
  name: chef_zero
  require_chef_omnibus: 13

platforms:
  # https://hub.docker.com/_/centos/
  - name: centos-6
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[test::yum_utils]
      - recipe[yum-nginx]
      - recipe[nginx-pkg]
    includes:
      - centos-6
      - centos-7

  - name: mainline
    run_list:
      - recipe[test::yum_utils]
      - recipe[yum-nginx]
      - recipe[nginx-pkg]
    attributes:
      yum-nginx:
        repos:
          nginx-stable:
            managed: false
          nginx-mainline:
            managed: true
    includes:
      - centos-6
      - centos-7

  - name: stable_source
    run_list:
      - recipe[test::yum_utils]
      - recipe[yum-nginx]
      - recipe[test::install_nginx_source]
    includes:
      - centos-6
      - centos-7
    attributes:
      yum-nginx:
        repos:
          nginx-stable-source:
            managed: true

  - name: mainline_source
    run_list:
      - recipe[test::yum_utils]
      - recipe[yum-nginx]
      - recipe[test::install_nginx_source]
    includes:
      - centos-6
      - centos-7
    attributes:
      yum-nginx:
        repos:
          nginx-mainline:
            managed: true
          nginx-mainline-source:
            managed: true
