driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 13

platforms:
  # https://github.com/chef/bento
  - name: centos-6.9
  - name: centos-7.4

suites:
  - name: default
    run_list:
      - recipe[test::yum_utils]
      - recipe[new-yum-nginx]
      - recipe[nginx-pkg]
    includes:
      - centos-6.9
      - centos-7.4

  - name: mainline
    run_list:
      - recipe[test::yum_utils]
      - recipe[new-yum-nginx]
      - recipe[nginx-pkg]
    attributes:
      yum-nginx:
        repos:
          nginx-stable:
            managed: false
          nginx-mainline:
            managed: true
    includes:
      - centos-6.9
      - centos-7.4

  - name: stable_source
    run_list:
      - recipe[test::yum_utils]
      - recipe[new-yum-nginx]
      - recipe[test::install_nginx_source]
    includes:
      - centos-6.9
      - centos-7.4
    attributes:
      yum-nginx:
        repos:
          nginx-stable-source:
            managed: true

  - name: mainline_source
    run_list:
      - recipe[test::yum_utils]
      - recipe[new-yum-nginx]
      - recipe[test::install_nginx_source]
    includes:
      - centos-6.9
      - centos-7.4
    attributes:
      yum-nginx:
        repos:
          nginx-mainline:
            managed: true
          nginx-mainline-source:
            managed: true
