addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

env:
  - CHEF_LICENSE=accept

sudo: required

branches:
  only:
    - master

services:
  - docker

install:
  - bundle install

before_script:
  - eval "$(chef shell-init bash)"

script:
  - cookstyle
  - chefspec
  - kitchen verify

env:
  global:
    - USE_SYSTEM_GECODE=1
    - KITCHEN_LOCAL_YAML=kitchen.dokken.yml
    - CHEF_LICENSE=accept
