# http://www.invalidchecksum.net/2015/08/travis-ci-gce-docker-test-kitchen.html
language: ruby

sudo: required

services:
  - docker

before_install:
  - sudo apt-get update

install:
  - bundle install

script:
  - bundle exec rake style
  - bundle exec rake unit
  - bundle exec kitchen test -d never

env:
  global:
    - USE_SYSTEM_GECODE=1
    - KITCHEN_LOCAL_YAML=.kitchen.docker.yml
