addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

branches:
  only:
    - master

services:
  - docker

install:
  - bundle install

before_script:
  - eval "$(chef shell-init bash)"

env:
  - USE_SYSTEM_GECODE=1
  - KITCHEN_LOCAL_YAML=kitchen.dokken.yml
  - CHEF_LICENSE=accept
    script:
      - cookstyle
      - chefspec
      - kitchen verify
